
server:
  port: 8888


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lyj?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1874
#    username: sa
#    password: 123



mybatis:
  typeAliasesPackage: com.feng.oldfriend.entity
  mapperLocations: classpath:mappers/*.xml


debug: false

#logging:
#  level:
#    com.feng.oldfriend.dao: DEBUG