
server:
  port: 8080

#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/upm_datasource?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.feng.oldfriend.entity
  mapperLocations: classpath:mappers/*.xml


debug: false
