package com.feng.oldfriend.entity;

import java.io.Serializable;
import java.util.Date;

public class LyjAdvertisement implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_advertisement.lyj_advertisement_id
     *
     * @mbggenerated
     */
    private Integer lyjAdvertisementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_advertisement.lyj_advertisement_name
     *
     * @mbggenerated
     */
    private String lyjAdvertisementName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_advertisement.lyj_advertisement_imageurl
     *
     * @mbggenerated
     */
    private String lyjAdvertisementImageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_advertisement.lyj_advertisement_begindatetime
     *
     * @mbggenerated
     */
    private Date lyjAdvertisementBegindatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_advertisement.lyj_advertisement_enddatetime
     *
     * @mbggenerated
     */
    private Date lyjAdvertisementEnddatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_advertisement.lyj_advertisement_page
     *
     * @mbggenerated
     */
    private String lyjAdvertisementPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_advertisement.lyj_advertisement_pageurl
     *
     * @mbggenerated
     */
    private String lyjAdvertisementPageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lyj_advertisement
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_advertisement.lyj_advertisement_id
     *
     * @return the value of lyj_advertisement.lyj_advertisement_id
     *
     * @mbggenerated
     */
    public Integer getLyjAdvertisementId() {
        return lyjAdvertisementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_advertisement.lyj_advertisement_id
     *
     * @param lyjAdvertisementId the value for lyj_advertisement.lyj_advertisement_id
     *
     * @mbggenerated
     */
    public void setLyjAdvertisementId(Integer lyjAdvertisementId) {
        this.lyjAdvertisementId = lyjAdvertisementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_advertisement.lyj_advertisement_name
     *
     * @return the value of lyj_advertisement.lyj_advertisement_name
     *
     * @mbggenerated
     */
    public String getLyjAdvertisementName() {
        return lyjAdvertisementName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_advertisement.lyj_advertisement_name
     *
     * @param lyjAdvertisementName the value for lyj_advertisement.lyj_advertisement_name
     *
     * @mbggenerated
     */
    public void setLyjAdvertisementName(String lyjAdvertisementName) {
        this.lyjAdvertisementName = lyjAdvertisementName == null ? null : lyjAdvertisementName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_advertisement.lyj_advertisement_imageurl
     *
     * @return the value of lyj_advertisement.lyj_advertisement_imageurl
     *
     * @mbggenerated
     */
    public String getLyjAdvertisementImageurl() {
        return lyjAdvertisementImageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_advertisement.lyj_advertisement_imageurl
     *
     * @param lyjAdvertisementImageurl the value for lyj_advertisement.lyj_advertisement_imageurl
     *
     * @mbggenerated
     */
    public void setLyjAdvertisementImageurl(String lyjAdvertisementImageurl) {
        this.lyjAdvertisementImageurl = lyjAdvertisementImageurl == null ? null : lyjAdvertisementImageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_advertisement.lyj_advertisement_begindatetime
     *
     * @return the value of lyj_advertisement.lyj_advertisement_begindatetime
     *
     * @mbggenerated
     */
    public Date getLyjAdvertisementBegindatetime() {
        return lyjAdvertisementBegindatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_advertisement.lyj_advertisement_begindatetime
     *
     * @param lyjAdvertisementBegindatetime the value for lyj_advertisement.lyj_advertisement_begindatetime
     *
     * @mbggenerated
     */
    public void setLyjAdvertisementBegindatetime(Date lyjAdvertisementBegindatetime) {
        this.lyjAdvertisementBegindatetime = lyjAdvertisementBegindatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_advertisement.lyj_advertisement_enddatetime
     *
     * @return the value of lyj_advertisement.lyj_advertisement_enddatetime
     *
     * @mbggenerated
     */
    public Date getLyjAdvertisementEnddatetime() {
        return lyjAdvertisementEnddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_advertisement.lyj_advertisement_enddatetime
     *
     * @param lyjAdvertisementEnddatetime the value for lyj_advertisement.lyj_advertisement_enddatetime
     *
     * @mbggenerated
     */
    public void setLyjAdvertisementEnddatetime(Date lyjAdvertisementEnddatetime) {
        this.lyjAdvertisementEnddatetime = lyjAdvertisementEnddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_advertisement.lyj_advertisement_page
     *
     * @return the value of lyj_advertisement.lyj_advertisement_page
     *
     * @mbggenerated
     */
    public String getLyjAdvertisementPage() {
        return lyjAdvertisementPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_advertisement.lyj_advertisement_page
     *
     * @param lyjAdvertisementPage the value for lyj_advertisement.lyj_advertisement_page
     *
     * @mbggenerated
     */
    public void setLyjAdvertisementPage(String lyjAdvertisementPage) {
        this.lyjAdvertisementPage = lyjAdvertisementPage == null ? null : lyjAdvertisementPage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_advertisement.lyj_advertisement_pageurl
     *
     * @return the value of lyj_advertisement.lyj_advertisement_pageurl
     *
     * @mbggenerated
     */
    public String getLyjAdvertisementPageurl() {
        return lyjAdvertisementPageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_advertisement.lyj_advertisement_pageurl
     *
     * @param lyjAdvertisementPageurl the value for lyj_advertisement.lyj_advertisement_pageurl
     *
     * @mbggenerated
     */
    public void setLyjAdvertisementPageurl(String lyjAdvertisementPageurl) {
        this.lyjAdvertisementPageurl = lyjAdvertisementPageurl == null ? null : lyjAdvertisementPageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_advertisement
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lyjAdvertisementId=").append(lyjAdvertisementId);
        sb.append(", lyjAdvertisementName=").append(lyjAdvertisementName);
        sb.append(", lyjAdvertisementImageurl=").append(lyjAdvertisementImageurl);
        sb.append(", lyjAdvertisementBegindatetime=").append(lyjAdvertisementBegindatetime);
        sb.append(", lyjAdvertisementEnddatetime=").append(lyjAdvertisementEnddatetime);
        sb.append(", lyjAdvertisementPage=").append(lyjAdvertisementPage);
        sb.append(", lyjAdvertisementPageurl=").append(lyjAdvertisementPageurl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}