package com.feng.oldfriend.entity;

import java.io.Serializable;

public class LyjRequirementType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typeid
     *
     * @mbggenerated
     */
    private Integer lyjRequirementTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typename
     *
     * @mbggenerated
     */
    private String lyjRequirementTypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typeparentid
     *
     * @mbggenerated
     */
    private Integer lyjRequirementTypeparentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lyj_requirement_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typeid
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typeid
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementTypeid() {
        return lyjRequirementTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typeid
     *
     * @param lyjRequirementTypeid the value for lyj_requirement_type.lyj_requirement_typeid
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypeid(Integer lyjRequirementTypeid) {
        this.lyjRequirementTypeid = lyjRequirementTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typename
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typename
     *
     * @mbggenerated
     */
    public String getLyjRequirementTypename() {
        return lyjRequirementTypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typename
     *
     * @param lyjRequirementTypename the value for lyj_requirement_type.lyj_requirement_typename
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypename(String lyjRequirementTypename) {
        this.lyjRequirementTypename = lyjRequirementTypename == null ? null : lyjRequirementTypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typeparentid
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typeparentid
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementTypeparentid() {
        return lyjRequirementTypeparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typeparentid
     *
     * @param lyjRequirementTypeparentid the value for lyj_requirement_type.lyj_requirement_typeparentid
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypeparentid(Integer lyjRequirementTypeparentid) {
        this.lyjRequirementTypeparentid = lyjRequirementTypeparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirement_type
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lyjRequirementTypeid=").append(lyjRequirementTypeid);
        sb.append(", lyjRequirementTypename=").append(lyjRequirementTypename);
        sb.append(", lyjRequirementTypeparentid=").append(lyjRequirementTypeparentid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}