package com.feng.oldfriend.entity;

import java.io.Serializable;

public class LyjRequirementApply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_apply.lyj_requirement_applyid
     *
     * @mbggenerated
     */
    private Integer lyjRequirementApplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_apply.lyj_user_id
     *
     * @mbggenerated
     */
    private Integer lyjUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_apply.lyj_volunteer_id
     *
     * @mbggenerated
     */
    private Integer lyjVolunteerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_apply.lyj_requirement_applystate
     *
     * @mbggenerated
     */
    private Integer lyjRequirementApplystate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_apply.lyj_requirement_applycomment
     *
     * @mbggenerated
     */
    private String lyjRequirementApplycomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_apply.lyj_requirement_applystar
     *
     * @mbggenerated
     */
    private Integer lyjRequirementApplystar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_apply.lyj_requirement_applyrequirementid
     *
     * @mbggenerated
     */
    private Integer lyjRequirementApplyrequirementid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_apply.lyj_requirement_applyduration
     *
     * @mbggenerated
     */
    private Integer lyjRequirementApplyduration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lyj_requirement_apply
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_apply.lyj_requirement_applyid
     *
     * @return the value of lyj_requirement_apply.lyj_requirement_applyid
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementApplyid() {
        return lyjRequirementApplyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_apply.lyj_requirement_applyid
     *
     * @param lyjRequirementApplyid the value for lyj_requirement_apply.lyj_requirement_applyid
     *
     * @mbggenerated
     */
    public void setLyjRequirementApplyid(Integer lyjRequirementApplyid) {
        this.lyjRequirementApplyid = lyjRequirementApplyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_apply.lyj_user_id
     *
     * @return the value of lyj_requirement_apply.lyj_user_id
     *
     * @mbggenerated
     */
    public Integer getLyjUserId() {
        return lyjUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_apply.lyj_user_id
     *
     * @param lyjUserId the value for lyj_requirement_apply.lyj_user_id
     *
     * @mbggenerated
     */
    public void setLyjUserId(Integer lyjUserId) {
        this.lyjUserId = lyjUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_apply.lyj_volunteer_id
     *
     * @return the value of lyj_requirement_apply.lyj_volunteer_id
     *
     * @mbggenerated
     */
    public Integer getLyjVolunteerId() {
        return lyjVolunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_apply.lyj_volunteer_id
     *
     * @param lyjVolunteerId the value for lyj_requirement_apply.lyj_volunteer_id
     *
     * @mbggenerated
     */
    public void setLyjVolunteerId(Integer lyjVolunteerId) {
        this.lyjVolunteerId = lyjVolunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_apply.lyj_requirement_applystate
     *
     * @return the value of lyj_requirement_apply.lyj_requirement_applystate
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementApplystate() {
        return lyjRequirementApplystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_apply.lyj_requirement_applystate
     *
     * @param lyjRequirementApplystate the value for lyj_requirement_apply.lyj_requirement_applystate
     *
     * @mbggenerated
     */
    public void setLyjRequirementApplystate(Integer lyjRequirementApplystate) {
        this.lyjRequirementApplystate = lyjRequirementApplystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_apply.lyj_requirement_applycomment
     *
     * @return the value of lyj_requirement_apply.lyj_requirement_applycomment
     *
     * @mbggenerated
     */
    public String getLyjRequirementApplycomment() {
        return lyjRequirementApplycomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_apply.lyj_requirement_applycomment
     *
     * @param lyjRequirementApplycomment the value for lyj_requirement_apply.lyj_requirement_applycomment
     *
     * @mbggenerated
     */
    public void setLyjRequirementApplycomment(String lyjRequirementApplycomment) {
        this.lyjRequirementApplycomment = lyjRequirementApplycomment == null ? null : lyjRequirementApplycomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_apply.lyj_requirement_applystar
     *
     * @return the value of lyj_requirement_apply.lyj_requirement_applystar
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementApplystar() {
        return lyjRequirementApplystar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_apply.lyj_requirement_applystar
     *
     * @param lyjRequirementApplystar the value for lyj_requirement_apply.lyj_requirement_applystar
     *
     * @mbggenerated
     */
    public void setLyjRequirementApplystar(Integer lyjRequirementApplystar) {
        this.lyjRequirementApplystar = lyjRequirementApplystar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_apply.lyj_requirement_applyrequirementid
     *
     * @return the value of lyj_requirement_apply.lyj_requirement_applyrequirementid
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementApplyrequirementid() {
        return lyjRequirementApplyrequirementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_apply.lyj_requirement_applyrequirementid
     *
     * @param lyjRequirementApplyrequirementid the value for lyj_requirement_apply.lyj_requirement_applyrequirementid
     *
     * @mbggenerated
     */
    public void setLyjRequirementApplyrequirementid(Integer lyjRequirementApplyrequirementid) {
        this.lyjRequirementApplyrequirementid = lyjRequirementApplyrequirementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_apply.lyj_requirement_applyduration
     *
     * @return the value of lyj_requirement_apply.lyj_requirement_applyduration
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementApplyduration() {
        return lyjRequirementApplyduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_apply.lyj_requirement_applyduration
     *
     * @param lyjRequirementApplyduration the value for lyj_requirement_apply.lyj_requirement_applyduration
     *
     * @mbggenerated
     */
    public void setLyjRequirementApplyduration(Integer lyjRequirementApplyduration) {
        this.lyjRequirementApplyduration = lyjRequirementApplyduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirement_apply
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lyjRequirementApplyid=").append(lyjRequirementApplyid);
        sb.append(", lyjUserId=").append(lyjUserId);
        sb.append(", lyjVolunteerId=").append(lyjVolunteerId);
        sb.append(", lyjRequirementApplystate=").append(lyjRequirementApplystate);
        sb.append(", lyjRequirementApplycomment=").append(lyjRequirementApplycomment);
        sb.append(", lyjRequirementApplystar=").append(lyjRequirementApplystar);
        sb.append(", lyjRequirementApplyrequirementid=").append(lyjRequirementApplyrequirementid);
        sb.append(", lyjRequirementApplyduration=").append(lyjRequirementApplyduration);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}