package com.feng.oldfriend.entity;

import java.io.Serializable;
import java.util.Date;

public class LyjRequirementType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typeid
     *
     * @mbggenerated
     */
    private Integer lyjRequirementTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typename
     *
     * @mbggenerated
     */
    private String lyjRequirementTypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typecreateuser
     *
     * @mbggenerated
     */
    private Integer lyjRequirementTypecreateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typeapplyuser
     *
     * @mbggenerated
     */
    private Integer lyjRequirementTypeapplyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typeisvolunteer
     *
     * @mbggenerated
     */
    private Integer lyjRequirementTypeisvolunteer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typecity
     *
     * @mbggenerated
     */
    private String lyjRequirementTypecity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typearea
     *
     * @mbggenerated
     */
    private String lyjRequirementTypearea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typestreet
     *
     * @mbggenerated
     */
    private String lyjRequirementTypestreet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typecreatedatetime
     *
     * @mbggenerated
     */
    private Date lyjRequirementTypecreatedatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typebegindatetime
     *
     * @mbggenerated
     */
    private Date lyjRequirementTypebegindatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typenddatetime
     *
     * @mbggenerated
     */
    private Date lyjRequirementTypenddatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typerawaddress
     *
     * @mbggenerated
     */
    private String lyjRequirementTyperawaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typedescription
     *
     * @mbggenerated
     */
    private String lyjRequirementTypedescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typemaplocation
     *
     * @mbggenerated
     */
    private String lyjRequirementTypemaplocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement_type.lyj_requirement_typereward
     *
     * @mbggenerated
     */
    private Integer lyjRequirementTypereward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lyj_requirement_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typeid
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typeid
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementTypeid() {
        return lyjRequirementTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typeid
     *
     * @param lyjRequirementTypeid the value for lyj_requirement_type.lyj_requirement_typeid
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypeid(Integer lyjRequirementTypeid) {
        this.lyjRequirementTypeid = lyjRequirementTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typename
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typename
     *
     * @mbggenerated
     */
    public String getLyjRequirementTypename() {
        return lyjRequirementTypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typename
     *
     * @param lyjRequirementTypename the value for lyj_requirement_type.lyj_requirement_typename
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypename(String lyjRequirementTypename) {
        this.lyjRequirementTypename = lyjRequirementTypename == null ? null : lyjRequirementTypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typecreateuser
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typecreateuser
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementTypecreateuser() {
        return lyjRequirementTypecreateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typecreateuser
     *
     * @param lyjRequirementTypecreateuser the value for lyj_requirement_type.lyj_requirement_typecreateuser
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypecreateuser(Integer lyjRequirementTypecreateuser) {
        this.lyjRequirementTypecreateuser = lyjRequirementTypecreateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typeapplyuser
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typeapplyuser
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementTypeapplyuser() {
        return lyjRequirementTypeapplyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typeapplyuser
     *
     * @param lyjRequirementTypeapplyuser the value for lyj_requirement_type.lyj_requirement_typeapplyuser
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypeapplyuser(Integer lyjRequirementTypeapplyuser) {
        this.lyjRequirementTypeapplyuser = lyjRequirementTypeapplyuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typeisvolunteer
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typeisvolunteer
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementTypeisvolunteer() {
        return lyjRequirementTypeisvolunteer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typeisvolunteer
     *
     * @param lyjRequirementTypeisvolunteer the value for lyj_requirement_type.lyj_requirement_typeisvolunteer
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypeisvolunteer(Integer lyjRequirementTypeisvolunteer) {
        this.lyjRequirementTypeisvolunteer = lyjRequirementTypeisvolunteer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typecity
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typecity
     *
     * @mbggenerated
     */
    public String getLyjRequirementTypecity() {
        return lyjRequirementTypecity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typecity
     *
     * @param lyjRequirementTypecity the value for lyj_requirement_type.lyj_requirement_typecity
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypecity(String lyjRequirementTypecity) {
        this.lyjRequirementTypecity = lyjRequirementTypecity == null ? null : lyjRequirementTypecity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typearea
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typearea
     *
     * @mbggenerated
     */
    public String getLyjRequirementTypearea() {
        return lyjRequirementTypearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typearea
     *
     * @param lyjRequirementTypearea the value for lyj_requirement_type.lyj_requirement_typearea
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypearea(String lyjRequirementTypearea) {
        this.lyjRequirementTypearea = lyjRequirementTypearea == null ? null : lyjRequirementTypearea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typestreet
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typestreet
     *
     * @mbggenerated
     */
    public String getLyjRequirementTypestreet() {
        return lyjRequirementTypestreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typestreet
     *
     * @param lyjRequirementTypestreet the value for lyj_requirement_type.lyj_requirement_typestreet
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypestreet(String lyjRequirementTypestreet) {
        this.lyjRequirementTypestreet = lyjRequirementTypestreet == null ? null : lyjRequirementTypestreet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typecreatedatetime
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typecreatedatetime
     *
     * @mbggenerated
     */
    public Date getLyjRequirementTypecreatedatetime() {
        return lyjRequirementTypecreatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typecreatedatetime
     *
     * @param lyjRequirementTypecreatedatetime the value for lyj_requirement_type.lyj_requirement_typecreatedatetime
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypecreatedatetime(Date lyjRequirementTypecreatedatetime) {
        this.lyjRequirementTypecreatedatetime = lyjRequirementTypecreatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typebegindatetime
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typebegindatetime
     *
     * @mbggenerated
     */
    public Date getLyjRequirementTypebegindatetime() {
        return lyjRequirementTypebegindatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typebegindatetime
     *
     * @param lyjRequirementTypebegindatetime the value for lyj_requirement_type.lyj_requirement_typebegindatetime
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypebegindatetime(Date lyjRequirementTypebegindatetime) {
        this.lyjRequirementTypebegindatetime = lyjRequirementTypebegindatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typenddatetime
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typenddatetime
     *
     * @mbggenerated
     */
    public Date getLyjRequirementTypenddatetime() {
        return lyjRequirementTypenddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typenddatetime
     *
     * @param lyjRequirementTypenddatetime the value for lyj_requirement_type.lyj_requirement_typenddatetime
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypenddatetime(Date lyjRequirementTypenddatetime) {
        this.lyjRequirementTypenddatetime = lyjRequirementTypenddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typerawaddress
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typerawaddress
     *
     * @mbggenerated
     */
    public String getLyjRequirementTyperawaddress() {
        return lyjRequirementTyperawaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typerawaddress
     *
     * @param lyjRequirementTyperawaddress the value for lyj_requirement_type.lyj_requirement_typerawaddress
     *
     * @mbggenerated
     */
    public void setLyjRequirementTyperawaddress(String lyjRequirementTyperawaddress) {
        this.lyjRequirementTyperawaddress = lyjRequirementTyperawaddress == null ? null : lyjRequirementTyperawaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typedescription
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typedescription
     *
     * @mbggenerated
     */
    public String getLyjRequirementTypedescription() {
        return lyjRequirementTypedescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typedescription
     *
     * @param lyjRequirementTypedescription the value for lyj_requirement_type.lyj_requirement_typedescription
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypedescription(String lyjRequirementTypedescription) {
        this.lyjRequirementTypedescription = lyjRequirementTypedescription == null ? null : lyjRequirementTypedescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typemaplocation
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typemaplocation
     *
     * @mbggenerated
     */
    public String getLyjRequirementTypemaplocation() {
        return lyjRequirementTypemaplocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typemaplocation
     *
     * @param lyjRequirementTypemaplocation the value for lyj_requirement_type.lyj_requirement_typemaplocation
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypemaplocation(String lyjRequirementTypemaplocation) {
        this.lyjRequirementTypemaplocation = lyjRequirementTypemaplocation == null ? null : lyjRequirementTypemaplocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement_type.lyj_requirement_typereward
     *
     * @return the value of lyj_requirement_type.lyj_requirement_typereward
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementTypereward() {
        return lyjRequirementTypereward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement_type.lyj_requirement_typereward
     *
     * @param lyjRequirementTypereward the value for lyj_requirement_type.lyj_requirement_typereward
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypereward(Integer lyjRequirementTypereward) {
        this.lyjRequirementTypereward = lyjRequirementTypereward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirement_type
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lyjRequirementTypeid=").append(lyjRequirementTypeid);
        sb.append(", lyjRequirementTypename=").append(lyjRequirementTypename);
        sb.append(", lyjRequirementTypecreateuser=").append(lyjRequirementTypecreateuser);
        sb.append(", lyjRequirementTypeapplyuser=").append(lyjRequirementTypeapplyuser);
        sb.append(", lyjRequirementTypeisvolunteer=").append(lyjRequirementTypeisvolunteer);
        sb.append(", lyjRequirementTypecity=").append(lyjRequirementTypecity);
        sb.append(", lyjRequirementTypearea=").append(lyjRequirementTypearea);
        sb.append(", lyjRequirementTypestreet=").append(lyjRequirementTypestreet);
        sb.append(", lyjRequirementTypecreatedatetime=").append(lyjRequirementTypecreatedatetime);
        sb.append(", lyjRequirementTypebegindatetime=").append(lyjRequirementTypebegindatetime);
        sb.append(", lyjRequirementTypenddatetime=").append(lyjRequirementTypenddatetime);
        sb.append(", lyjRequirementTyperawaddress=").append(lyjRequirementTyperawaddress);
        sb.append(", lyjRequirementTypedescription=").append(lyjRequirementTypedescription);
        sb.append(", lyjRequirementTypemaplocation=").append(lyjRequirementTypemaplocation);
        sb.append(", lyjRequirementTypereward=").append(lyjRequirementTypereward);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}