package com.feng.oldfriend.entity;

import lombok.AllArgsConstructor;

import java.io.Serializable;

@AllArgsConstructor
public class LyjRequirementtypeRelation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirementtype_relation.lyj_requirement_id
     *
     * @mbggenerated
     */
    private Integer lyjRequirementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirementtype_relation.lyj_requirement_typeid
     *
     * @mbggenerated
     */
    private Integer lyjRequirementTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lyj_requirementtype_relation
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirementtype_relation.lyj_requirement_id
     *
     * @return the value of lyj_requirementtype_relation.lyj_requirement_id
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementId() {
        return lyjRequirementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirementtype_relation.lyj_requirement_id
     *
     * @param lyjRequirementId the value for lyj_requirementtype_relation.lyj_requirement_id
     *
     * @mbggenerated
     */
    public void setLyjRequirementId(Integer lyjRequirementId) {
        this.lyjRequirementId = lyjRequirementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirementtype_relation.lyj_requirement_typeid
     *
     * @return the value of lyj_requirementtype_relation.lyj_requirement_typeid
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementTypeid() {
        return lyjRequirementTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirementtype_relation.lyj_requirement_typeid
     *
     * @param lyjRequirementTypeid the value for lyj_requirementtype_relation.lyj_requirement_typeid
     *
     * @mbggenerated
     */
    public void setLyjRequirementTypeid(Integer lyjRequirementTypeid) {
        this.lyjRequirementTypeid = lyjRequirementTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirementtype_relation
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lyjRequirementId=").append(lyjRequirementId);
        sb.append(", lyjRequirementTypeid=").append(lyjRequirementTypeid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}