package com.feng.oldfriend.entity;

import java.io.Serializable;

public class LyjRequirement implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement.lyj_requirement_id
     *
     * @mbggenerated
     */
    private Integer lyjRequirementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement.lyj_requirement_name
     *
     * @mbggenerated
     */
    private String lyjRequirementName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_requirement.lyj_requirement_description
     *
     * @mbggenerated
     */
    private String lyjRequirementDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lyj_requirement
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement.lyj_requirement_id
     *
     * @return the value of lyj_requirement.lyj_requirement_id
     *
     * @mbggenerated
     */
    public Integer getLyjRequirementId() {
        return lyjRequirementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement.lyj_requirement_id
     *
     * @param lyjRequirementId the value for lyj_requirement.lyj_requirement_id
     *
     * @mbggenerated
     */
    public void setLyjRequirementId(Integer lyjRequirementId) {
        this.lyjRequirementId = lyjRequirementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement.lyj_requirement_name
     *
     * @return the value of lyj_requirement.lyj_requirement_name
     *
     * @mbggenerated
     */
    public String getLyjRequirementName() {
        return lyjRequirementName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement.lyj_requirement_name
     *
     * @param lyjRequirementName the value for lyj_requirement.lyj_requirement_name
     *
     * @mbggenerated
     */
    public void setLyjRequirementName(String lyjRequirementName) {
        this.lyjRequirementName = lyjRequirementName == null ? null : lyjRequirementName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_requirement.lyj_requirement_description
     *
     * @return the value of lyj_requirement.lyj_requirement_description
     *
     * @mbggenerated
     */
    public String getLyjRequirementDescription() {
        return lyjRequirementDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_requirement.lyj_requirement_description
     *
     * @param lyjRequirementDescription the value for lyj_requirement.lyj_requirement_description
     *
     * @mbggenerated
     */
    public void setLyjRequirementDescription(String lyjRequirementDescription) {
        this.lyjRequirementDescription = lyjRequirementDescription == null ? null : lyjRequirementDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirement
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lyjRequirementId=").append(lyjRequirementId);
        sb.append(", lyjRequirementName=").append(lyjRequirementName);
        sb.append(", lyjRequirementDescription=").append(lyjRequirementDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}