package com.feng.oldfriend.entity;

import java.io.Serializable;

public class LyjVolunteer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_volunteer.lyj_volunteer_id
     *
     * @mbggenerated
     */
    private Integer lyjVolunteerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_volunteer.lyj_user_id
     *
     * @mbggenerated
     */
    private Integer lyjUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_volunteer.lyj_volunteer_id
     *
     * @return the value of lyj_volunteer.lyj_volunteer_id
     *
     * @mbggenerated
     */
    public Integer getLyjVolunteerId() {
        return lyjVolunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_volunteer.lyj_volunteer_id
     *
     * @param lyjVolunteerId the value for lyj_volunteer.lyj_volunteer_id
     *
     * @mbggenerated
     */
    public void setLyjVolunteerId(Integer lyjVolunteerId) {
        this.lyjVolunteerId = lyjVolunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_volunteer.lyj_user_id
     *
     * @return the value of lyj_volunteer.lyj_user_id
     *
     * @mbggenerated
     */
    public Integer getLyjUserId() {
        return lyjUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_volunteer.lyj_user_id
     *
     * @param lyjUserId the value for lyj_volunteer.lyj_user_id
     *
     * @mbggenerated
     */
    public void setLyjUserId(Integer lyjUserId) {
        this.lyjUserId = lyjUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lyjVolunteerId=").append(lyjVolunteerId);
        sb.append(", lyjUserId=").append(lyjUserId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}