package com.feng.oldfriend.entity;

import java.io.Serializable;

public class LyjVolunteer implements Serializable {

    private Integer lyjUserApplystate;

    public Integer getLyjUserApplystate() {
        return lyjUserApplystate;
    }

    public void setLyjUserApplystate(Integer lyjUserApplystate) {
        this.lyjUserApplystate = lyjUserApplystate;
    }

    private String lyjUsername;

    public String getLyjUsername() {
        return lyjUsername;
    }

    public void setLyjUsername(String lyjUsername) {
        this.lyjUsername = lyjUsername;
    }

    public String getLyjUserId() {
        return lyjUserId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_volunteer.lyj_volunteer_id
     *
     * @mbggenerated
     */
    private Integer lyjVolunteerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyj_volunteer.lyj_user_id
     *
     * @mbggenerated
     */
    private String lyjUserId;

    public void setLyjUserId(String lyjUserId) {
        this.lyjUserId = lyjUserId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyj_volunteer.lyj_volunteer_id
     *
     * @return the value of lyj_volunteer.lyj_volunteer_id
     *
     * @mbggenerated
     */
    public Integer getLyjVolunteerId() {
        return lyjVolunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyj_volunteer.lyj_volunteer_id
     *
     * @param lyjVolunteerId the value for lyj_volunteer.lyj_volunteer_id
     *
     * @mbggenerated
     */
    public void setLyjVolunteerId(Integer lyjVolunteerId) {
        this.lyjVolunteerId = lyjVolunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lyjVolunteerId=").append(lyjVolunteerId);
        sb.append(", lyjUserId=").append(lyjUserId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
