package com.feng.oldfriend.dao;

import com.feng.oldfriend.entity.LyjAdvertisement;
import java.util.List;

public interface LyjAdvertisementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_advertisement
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lyjAdvertisementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_advertisement
     *
     * @mbggenerated
     */
    int insert(LyjAdvertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_advertisement
     *
     * @mbggenerated
     */
    LyjAdvertisement selectByPrimaryKey(Integer lyjAdvertisementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_advertisement
     *
     * @mbggenerated
     */
    List<LyjAdvertisement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_advertisement
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LyjAdvertisement record);
}