package com.feng.oldfriend.dao;

import com.feng.oldfriend.entity.LyjRequirementApply;
import com.feng.oldfriend.enums.ApplyStatus;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface LyjRequirementApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirement_apply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lyjRequirementApplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirement_apply
     *
     * @mbggenerated
     */
    int insert(LyjRequirementApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirement_apply
     *
     * @mbggenerated
     */
    LyjRequirementApply selectByPrimaryKey(Integer lyjRequirementApplyid);

    /**
     * create by: yangchenxiao
     * create time: 2019/7/24 22:02
     * description: 根据需求ID查找到所有的需求申请
     */
    List<LyjRequirementApply> selectByRequirementId(@Param("lyjRequirementId") Integer lyjRequirementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirement_apply
     *
     * @mbggenerated
     */
    List<LyjRequirementApply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirement_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LyjRequirementApply record);

    /**
     * create by: yangchenxiao
     * create time: 2019/7/24 21:57
     * description: 将除了某个申请ID外的其他同一申请需求的申请置为申请失败
     */
    int updateApplyFailed(@Param("requirementId")Integer requirementId,
                          @Param("requirementApplyId") Integer requirementApplyId,
                          @Param("lyjRequirementApplystate")Integer lyjRequirementApplystate);
}