package com.feng.oldfriend.dao;

import com.feng.oldfriend.entity.LyjRequirementtypeRelation;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LyjRequirementtypeRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirementtype_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("lyjRequirementId") Integer lyjRequirementId, @Param("lyjRequirementTypeid") Integer lyjRequirementTypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirementtype_relation
     *
     * @mbggenerated
     */
    int insert(LyjRequirementtypeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirementtype_relation
     *
     * @mbggenerated
     */
    List<LyjRequirementtypeRelation> selectAll();
}