package com.feng.oldfriend.dao;

import com.feng.oldfriend.entity.LyjRequirementtypeRelation;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface LyjRequirementtypeRelationMapper {

    /**
     * create by: yangchenxiao
     * create time: 2019/7/21 14:44
     * description: 根据所有的需求类型ID找到所有的需求ID
     */
    List<Integer> getRequirementidsByTypeid(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirementtype_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("lyjRequirementId") Integer lyjRequirementId, @Param("lyjRequirementTypeid") Integer lyjRequirementTypeid);

    /**
     * create by: yangchenxiao
     * create time: 2019/7/21 16:47
     * description: 根据需求ID删除所有的关系数据
     */
    int deleteByRequirementId(@Param("lyjRequirementId") Integer lyjRequirementId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirementtype_relation
     *
     * @mbggenerated
     */
    int insert(LyjRequirementtypeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_requirementtype_relation
     *
     * @mbggenerated
     */
    List<LyjRequirementtypeRelation> selectAll();
}