package com.feng.oldfriend.dao;

import com.feng.oldfriend.entity.LyjUser;
import java.util.List;

public interface LyjUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lyjUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_user
     *
     * @mbggenerated
     */
    int insert(LyjUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_user
     *
     * @mbggenerated
     */
    LyjUser selectByPrimaryKey(Integer lyjUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_user
     *
     * @mbggenerated
     */
    List<LyjUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LyjUser record);
}