package com.feng.oldfriend.dao;

import com.feng.oldfriend.entity.LyjUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface LyjUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lyjUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_user
     *
     * @mbggenerated
     */
    int insert(LyjUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_user
     *
     * @mbggenerated
     */
    LyjUser selectByPrimaryKey(Integer lyjUserId);

    /**
     * create by: yangchenxiao
     * create time: 2019/8/11 16:43
     * description: 用户登录验证
     */
    LyjUser userLogin(@Param("phone")String phone,@Param("password")String password);

    /**
     * create by: yangchenxiao
     * create time: 2019/8/11 16:43
     * description: 根据唯一标识找到用户
     */
    LyjUser findUserByUUID(@Param("uuid")String uuid);

    /**
     * create by: yangchenxiao
     * create time: 2019/8/12 21:40
     * description: 根据手机号码找到用户
     */
    Integer findUserByPhone(@Param("phone")String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_user
     *
     * @mbggenerated
     */
    List<LyjUser> selectAll();

    /**
     * create by: yangchenxiao
     * create time: 2019/7/28 15:02
     * description: 根据搜索条件对所有的用户进行查找
     */
    List<LyjUser> getUsers(@Param("searchText") String searchText);

    Integer getUsersCount(@Param("searchText") String searchText);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LyjUser record);

    int updateByPrimaryKeyForVolunteer(LyjUser record);
}
