package com.feng.oldfriend.dao;

import com.feng.oldfriend.entity.LyjVolunteer;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface LyjVolunteerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lyjVolunteerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    int insert(LyjVolunteer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    LyjVolunteer selectByPrimaryKey(Integer lyjVolunteerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    List<LyjVolunteer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LyjVolunteer record);
}