package com.feng.oldfriend.dao;

import com.feng.oldfriend.entity.LyjUser;
import com.feng.oldfriend.entity.LyjVolunteer;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface LyjVolunteerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lyjVolunteerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    @Options(useGeneratedKeys=true, keyProperty="lyjVolunteerId", keyColumn="lyj_volunteer_id")
    void insert(LyjVolunteer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    LyjVolunteer selectByPrimaryKey(Integer lyjVolunteerId);

    /**
     * create by: yangchenxiao
     * create time: 2019/7/29 21:53
     * description: 根据用户ID找到对应的义工
     */
    LyjVolunteer getVolunteerByUserId(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    List<LyjVolunteer> selectAll();

    Integer selectAllCount();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyj_volunteer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LyjVolunteer record);
}
